In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [16]:
df = pd.read_csv("housing.csv")
df = df.dropna()
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [3]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [4]:
df['ocean_proximity'] = df.groupby('ocean_proximity')["median_house_value"].transform("mean")

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df1 = pd.DataFrame(scaler.fit_transform(df),columns = df.columns)
df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.211155  0.567481            0.784314     0.022331        0.019863   
1       0.212151  0.565356            0.392157     0.180503        0.171477   
2       0.210159  0.564293            1.000000     0.037260        0.029330   
3       0.209163  0.564293            1.000000     0.032352        0.036313   
4       0.209163  0.564293            1.000000     0.041330        0.043296   
...          ...       ...                 ...          ...             ...   
20428   0.324701  0.737513            0.470588     0.042296        0.057883   
20429   0.312749  0.738576            0.333333     0.017676        0.023122   
20430   0.311753  0.732200            0.313725     0.057277        0.075109   
20431   0.301793  0.732200            0.333333     0.047256        0.063315   
20432   0.309761  0.725824            0.294118     0.070782        0.095438   

       population  households  median_income  median_house_value  \
0        0.008941    0.020556       0.539668            0.902266   
1        0.067210    0.186976       0.538027            0.708247   
2        0.013818    0.028943       0.466028            0.695051   
3        0.015555    0.035849       0.354699            0.672783   
4        0.015752    0.042427       0.230776            0.674638   
...           ...         ...            ...                 ...   
20428    0.023599    0.054103       0.073130            0.130105   
20429    0.009894    0.018582       0.141853            0.128043   
20430    0.028140    0.071041       0.082764            0.159383   
20431    0.020684    0.057227       0.094295            0.143713   
20432    0.038790    0.086992       0.130253            0.153403   

       ocean_proximity  
0              0.52587  
1              0.52587  
2              0.52587  
3              0.52587  
4              0.52587  
...                ...  
20428          0.00000  
20429          0.00000  
20430          0.00000  
20431          0.00000  
20432          0.00000  

[20433 rows x 10 columns]

In [17]:
df1.fillna(999,inplace=True)
#inplace=true makes the changes permanent
df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.211155  0.567481            0.784314     0.022331        0.019863   
1       0.212151  0.565356            0.392157     0.180503        0.171477   
2       0.210159  0.564293            1.000000     0.037260        0.029330   
3       0.209163  0.564293            1.000000     0.032352        0.036313   
4       0.209163  0.564293            1.000000     0.041330        0.043296   
...          ...       ...                 ...          ...             ...   
20428   0.324701  0.737513            0.470588     0.042296        0.057883   
20429   0.312749  0.738576            0.333333     0.017676        0.023122   
20430   0.311753  0.732200            0.313725     0.057277        0.075109   
20431   0.301793  0.732200            0.333333     0.047256        0.063315   
20432   0.309761  0.725824            0.294118     0.070782        0.095438   

       population  households  median_income  median_house_value  \
0        0.008941    0.020556       0.539668            0.902266   
1        0.067210    0.186976       0.538027            0.708247   
2        0.013818    0.028943       0.466028            0.695051   
3        0.015555    0.035849       0.354699            0.672783   
4        0.015752    0.042427       0.230776            0.674638   
...           ...         ...            ...                 ...   
20428    0.023599    0.054103       0.073130            0.130105   
20429    0.009894    0.018582       0.141853            0.128043   
20430    0.028140    0.071041       0.082764            0.159383   
20431    0.020684    0.057227       0.094295            0.143713   
20432    0.038790    0.086992       0.130253            0.153403   

       ocean_proximity  
0              0.52587  
1              0.52587  
2              0.52587  
3              0.52587  
4              0.52587  
...                ...  
20428          0.00000  
20429          0.00000  
20430          0.00000  
20431          0.00000  
20432          0.00000  

[20433 rows x 10 columns]

In [6]:
y = df1['median_house_value']
x = df1.drop('median_house_value',axis = 1)
y.shape,x.shape


((20433,), (20433, 9))

In [18]:
df1 = df1.drop('ocean_proximity',axis=1)

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((14303, 9), (14303,), (6130, 9), (6130,))

In [20]:
linear_model = LinearRegression()
lasso_model = Lasso(alpha = 0.1)
ridge_model = Ridge(alpha = 0.1)
#This alpha is the regularization prameter which we are adding as an error term to our model
# we are not taking the errors add in the feature we only adding the regularisation parameterlin


In [23]:
linear_model.fit(x_train,y_train)

LinearRegression()

In [24]:
lasso_model.fit(x_train,y_train)


Lasso(alpha=0.1)

In [25]:
ridge_model.fit(x_train,y_train)


Ridge(alpha=0.1)

In [26]:
linear_model.coef_

array([-0.55214682, -0.50578279,  0.10736662, -0.46844117,  1.30384261,
       -2.71123198,  0.57605975,  1.1654101 ,  0.16907316])

In [27]:
lasso_model.coef_

array([-0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.])

In [28]:
ridge_model.coef_

array([-0.54838769, -0.5016199 ,  0.10744731, -0.45334181,  1.27525396,
       -2.60741488,  0.54489656,  1.16347879,  0.17092359])

In [29]:
linear_model.intercept_

0.4247615059275749

In [30]:
lasso_model.intercept_

0.3941412728199548

In [31]:
ridge_model.intercept_

0.42119583357232104

In [32]:
linear_model.score(x_test,y_test),lasso_model.score(x_test,y_test),ridge_model.score(x_test,y_test)

(0.6575046352886071, -0.0004057951641056601, 0.6572676355484552)

In [33]:
linear_train_mse = mean_squared_error(y_train,linear_model.predict(x_train))
linear_test_mse = mean_squared_error(y_test,linear_model.predict(x_test))

In [34]:
linear_train_mse

0.02015691385237188

In [35]:
linear_test_mse

0.019876769863057614

In [36]:
lasso_train_mse = mean_squared_error(y_train,lasso_model.predict(x_train))
lasso_test_mse = mean_squared_error(y_test,lasso_model.predict(x_test))

In [37]:
lasso_train_mse,lasso_test_mse

(0.05604403151666088, 0.058058700376579515)

In [38]:
ridge_train_mse = mean_squared_error(y_train,ridge_model.predict(x_train))
ridge_test_mse = mean_squared_error(y_test,ridge_model.predict(x_test))

In [39]:
ridge_train_mse
ridge_test_mse


0.019890524178525715